// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KoiOrderingSystemInJapan.Data.Models;

public partial class Feedback
{
    public int FeedbackId { get; set; }

    public int CustomerId { get; set; }

    public int? OrderKoiId { get; set; }

    public int? OrderTripId { get; set; }

    public byte? ServiceRating { get; set; }

    public byte? ProductRating { get; set; }

    public string Comment { get; set; }

    public string Reply { get; set; }

    public DateTime? FeedbackDate { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public virtual User Customer { get; set; }

    public virtual OrderKoiFish OrderKoi { get; set; }

    public virtual OrderTrip OrderTrip { get; set; }
}