// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KoiOrderingSystemInJapan.Data.Models;

public partial class OrderKoiFish
{
    public int OrderKoiId { get; set; }

    public int CustomerId { get; set; }

    public DateTime? OrderDate { get; set; }

    public decimal TotalPrice { get; set; }

    public decimal? Deposit { get; set; }

    public decimal RemainingBalance { get; set; }

    public DateOnly? DeliveryDate { get; set; }

    public DateTime? CreatedDate { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public string DeliveryMethod { get; set; }

    public string SpecialInstructions { get; set; }

    public string CancellationReason { get; set; }

    public int InsuranceId { get; set; }

    public int? Status { get; set; }

    public virtual User Customer { get; set; }

    public virtual ICollection<Feedback> Feedbacks { get; set; } = new List<Feedback>();

    public virtual InsurancePolicy Insurance { get; set; }

    public virtual ICollection<OrderHistory> OrderHistories { get; set; } = new List<OrderHistory>();

    public virtual ICollection<OrderKoiFishDetail> OrderKoiFishDetails { get; set; } = new List<OrderKoiFishDetail>();

    public virtual ICollection<Payment> Payments { get; set; } = new List<Payment>();

    public virtual ICollection<RefundRequest> RefundRequests { get; set; } = new List<RefundRequest>();
}