// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using KoiOrderingSystemInJapan.Common.Enum;
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace KoiOrderingSystemInJapan.Data.Models;

public partial class RefundRequest
{
    public int RefundRequestId { get; set; }

    public int OrderKoiId { get; set; }

    public DateTime? RequestDate { get; set; }

    public decimal? RefundAmount { get; set; }

    public string Reason { get; set; }

    public DateTime? ProcessedDate { get; set; }

    [JsonConverter(typeof(JsonStringEnumConverter))]
    public RefundRequestStatus Status { get; set; }

    public virtual OrderKoiFish OrderKoi { get; set; }
}