// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KoiOrderingSystemInJapan.Data.Models;

public partial class Schedule
{
    public int ScheduleId { get; set; }

    public int TripId { get; set; }

    public int FarmId { get; set; }

    public int VisitOrder { get; set; }

    public DateOnly VisitDate { get; set; }

    public TimeOnly StartTime { get; set; }

    public TimeOnly EndTime { get; set; }

    public DateTime? CreatedDate { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public virtual Farm Farm { get; set; }

    public virtual Trip Trip { get; set; }
}