// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KoiOrderingSystemInJapan.Data.Models;

public partial class TripSchedule
{
    public int ScheduleId { get; set; }

    public int TripId { get; set; }

    public DateOnly StartDate { get; set; }

    public DateOnly EndDate { get; set; }

    public int? MaxParticipants { get; set; }

    public bool? IsActive { get; set; }

    public DateTime? CreatedDate { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public int? CreatedBy { get; set; }

    public int? UpdatedBy { get; set; }

    public virtual ICollection<CheckIn> CheckIns { get; set; } = new List<CheckIn>();

    public virtual ICollection<OrderTrip> OrderTrips { get; set; } = new List<OrderTrip>();

    public virtual ICollection<ScheduleFarm> ScheduleFarms { get; set; } = new List<ScheduleFarm>();

    public virtual Trip Trip { get; set; }
}